class AppStrings {
  static const Map<String, Map<String, String>> data = {
    'en': {
      'login': 'Login',
      'email': 'Email',
      'password': 'Password',
      'forgot_password': 'Forgot password?',
      'login_button': 'Login',
      'app_slogan': 'Management App for Doctors',
      'error': 'Error',
      'ok': 'OK',
      'no_data': 'No data',
      'select': 'Select',
      'unselected': 'Unselected',
      'add': 'Add',
      'login_failed': 'Login failed. Please check your email and password.',
      'email_required': 'Please enter email',
      'email_invalid': 'Invalid email format',
      'password_required': 'Please enter password',
      'password_invalid':
          'Password must include 8+ characters, letters, and numbers',
      'forgot_password_title': 'Forgot Password',
      'reset_email_sent_message':
          'If an account exists, a reset code has been sent.',
      'reset_email_send_failed':
          'Failed to send reset email. Please try again.',
      'enter_email_instruction':
          'Enter your email address to receive a reset code.',
      'verify_code_title': 'Verify Code',
      'verify_code_instruction': 'Enter the 6-digit code sent to ',
      'otp_code_label': 'OTP Code',
      'otp_required_error': 'Please enter the code',
      'otp_length_error': 'Code must be 6 digits',
      'verify_code_success': 'Code verified successfully.',
      'verify_code_invalid': 'Invalid or expired code.',
      'verifying': 'Verifying...',
      'verify': 'Verify',
      'reset_password_page_title': 'Reset Password',
      'reset_password_success': 'Password reset successfully. Please log in.',
      'reset_password_failed': 'Failed to reset password. Please try again.',
      'password_required_error': 'Please enter a new password',
      'confirm_password_required_error': 'Please confirm your password',
      'settings': 'Settings',
      'language': 'Language',
      'english': 'English',
      'vietnamese': 'Vietnamese',
      'logout': 'Logout',
      'change_password': 'Change Password',
      'profile': 'Profile',
      'theme': 'Theme',
      'dark_mode': 'Dark Mode',
      'light_mode': 'Light Mode',
      'system_mode': 'System Mode',
      'personal_information': 'Personal Information',
      'specialty_management': 'Specialty Management',
      'location_management': 'Location Management',
      'office_hours_management': 'Office Hours Management',
      'patient_management': 'Patient Management',
      'permission_management': 'Permission Management',
      'account_management': 'Account Management',
      'logout_confirmation_title': 'Confirm Logout',
      'logout_confirmation_message': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'logout_failed': 'Logout failed, please try again!',
      'schedule_management': 'Schedule Management',
      'answer_questions': 'Answer Questions',
      'patient_reviews': 'Patient Reviews',
      'profile_management': 'Profile Management',
      'appointment_management': 'Appointment Management',
      'doctor_management': 'Doctor Management',
      'qa_management': 'Q&A Management',
      'blog_management': 'Blog Management',
      'admin_account_management': 'Admin Account Management',
      'logged_in_as_admin': 'You are logged in as Admin',
      'logged_in_as_super_admin': 'You are logged in as Super Admin',
      'error_load_doctor_profile': 'Cannot load doctor profile.',
      'error_load_specialty_profile': 'Cannot load specialty profile.',
      'error_occurred': 'An error occurred: ',
      // Appointment Module
      'appointments_title': 'Appointments',
      'loading_list': 'Loading list...',
      'select_doctor': 'Select Doctor',
      'step_patient': 'Patient',
      'step_service': 'Service',
      'step_schedule': 'Schedule',
      'step_details': 'Details',
      'step_confirm': 'Confirm',
      'create_appointment_title': 'Create New Appointment',
      'back': 'Back',
      'continue_step': 'Continue',
      'confirm_booking': 'Confirm Booking',
      'error_select_patient': 'Please select a patient',
      'error_select_service_info': 'Please select full service information',
      'error_select_datetime': 'Please select date and time',
      'search_select_patient': 'Search and Select Patient',
      'search_patient_hint': 'Enter name, email or phone',
      'no_email': 'No email',
      'no_phone': 'No phone',
      'service_info': 'Service Information',
      'location': 'Location',
      'specialty': 'Specialty',
      'doctor': 'Doctor',
      'select_time': 'Select Time',
      'selected_slot': 'Selected: ',
      'details_info': 'Details Information',
      'reason_for_visit': 'Reason for visit',
      'additional_notes': 'Additional notes',
      'examination_price': 'Examination Price',
      'currency': 'Currency',
      'confirm_info': 'Confirm Information',
      'time': 'Time',
      'reason': 'Reason',
      'notes': 'Notes',
      'price': 'Price',
      'none': 'None',
      'not_entered': 'Not entered',
      'booking_success': 'Booking successful!',
      'update_appointment_title': 'Update Appointment',
      'status': 'Status',
      'price_vnd': 'Price (VND)',
      'error_invalid_number': 'Please enter a valid number',
      'save': 'Save',
      'update_success': 'Update successful',
      'error_occurred_short': 'An error occurred',
      'cancel_appointment_title': 'Cancel Appointment',
      'cancel_appointment_confirm':
          'Are you sure you want to cancel this appointment?',
      'cancel_reason_required': 'Cancellation reason *',
      'error_enter_reason': 'Please enter a reason',
      'close': 'Close',
      'cancel_success': 'Appointment cancelled',
      'reschedule_appointment_title': 'Reschedule Appointment',
      'confirm_appointment_title': 'Confirm Appointment',
      'confirm_appointment_message':
          'Are you sure you want to confirm this appointment?',
      'confirm': 'Confirm',
      'confirm_success': 'Appointment confirmed',
      'confirm_reschedule_title': 'Confirm Reschedule',
      'reschedule_confirm_message': 'Reschedule to ',
      'agree': 'Agree',
      'reschedule_success': 'Reschedule successful',
      'reschedule': 'Reschedule',
      'status_booked': 'Booked',
      'status_confirmed': 'Confirmed',
      'status_completed': 'Completed',
      'status_cancelled': 'Cancelled',
      'status_rescheduled': 'Rescheduled',
      'patient': 'Patient',
      'date_label': 'Date',
      'appointment_filter_title': 'Appointment Filter',
      'reset': 'Reset',
      'apply': 'Apply',
      'all_doctors': 'All Doctors',
      'work_location': 'Work Location',
      'all_locations': 'All Locations',
      'all_specialties': 'All Specialties',
      'calendar_settings_title': 'Calendar Settings',
      'display_hours': 'Display Hours',
      'card_appearance': 'Card Appearance',
      'background_color': 'Background Color',
      'dot': 'Dot',
      'mixed': 'Mixed',
      'working_days': 'Working Days',
      'save_changes': 'Save Changes',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      // Patient Module
      'patient_management_title': 'Patient Management',
      'offline_create_patient_error': 'Cannot create patient while offline',
      'search_patient': 'Search Patient',
      'offline_banner': 'You are offline. Data may be outdated.',
      'no_patients_found': 'No patients found.',
      'offline_edit_error': 'Cannot edit while offline',
      'edit': 'Edit',
      'offline_delete_error': 'Cannot delete/restore while offline',
      'restore': 'Restore',
      'delete': 'Delete',
      'deleted': 'Deleted',
      'create_patient_success': 'Patient created successfully',
      'create_patient_failed': 'Failed to create patient',
      'create_patient_title': 'Create New Patient',
      'update_patient_success': 'Patient updated successfully',
      'update_patient_failed': 'Failed to update patient',
      'update_patient_title': 'Update Patient',
      'confirm_delete_title': 'Confirm Delete',
      'confirm_delete_patient_message':
          'Are you sure you want to delete this patient?',
      'confirm_delete_patient_named':
          'Are you sure you want to delete patient ',
      'full_name': 'Full Name',
      'error_enter_full_name': 'Please enter full name',
      'phone_number': 'Phone Number',
      'date_of_birth': 'Date of Birth',
      'gender': 'Gender',
      'unknown': 'Unknown',
      'male': 'Male',
      'female': 'Female',
      'contact_address': 'Contact Address',
      'address': 'Address',
      'district': 'District',
      'province': 'Province',
      'years_old_suffix': 'years old',
      'create_new': 'Create New',
      'update': 'Update',
      // Admin Management Module
      'admin_management_title': 'Admin Management',
      'search_by_name_email': 'Search by name or email',
      'create_admin_account': 'Create Admin Account',
      'filter_sort': 'Filter & Sort',
      'all': 'All',
      'sort': 'Sort',
      'created_date': 'Created Date',
      'name': 'Name',
      'ascending': 'Ascending',
      'descending': 'Descending',
      'no_admins_found': 'No admins found',
      'edit_admin_account': 'Edit Admin Account',
      'confirm_delete_staff_message': 'Are you sure you want to delete ',
      'password_min_length': 'Password must be at least 6 characters',
      'password_max_length': 'Password must not exceed 50 characters',
      'delete_success': 'Deleted successfully',
      'delete_failed': 'Delete failed. Check password or try again.',
      'error_occurred_retry': 'An error occurred. Please try again.',
      'password_length_error': 'Password must be between 6 and 50 characters',
      'incorrect_password': 'Incorrect password',
      'forbidden_action': 'You do not have permission to perform this action',
      'too_many_requests': 'Too many requests. Please try again later!',
      'enter_super_admin_password': 'Enter Super Admin Password',
      'password_hint': 'Password 6-50 characters',
      'processing': 'Processing...',
      'new_password_optional': 'New password (leave blank if not changing)',
      'password_complexity_error':
          'Password must be at least 8 characters, contain letters and numbers',
      'phone_number_invalid': 'Phone number must be 10 digits',
      'date_of_birth_format': 'Date of Birth (dd/mm/yyyy)',
      'date_of_birth_required': 'Please select date of birth',
      'create': 'Create',
      'failed': 'failed',
      // Blog Module
      'blog_management_title': 'Blog Management',
      'search_blog_hint': 'Search by title',
      'no_blogs_found': 'No blogs found',
      'no_blogs_yet': 'No blogs yet',
      'add_new_blog_hint': 'Press "+" button to add new blog.',
      'try_search_again':
          'Try searching with different keywords or clear filters.',
      'create_blog_title': 'Create New Blog',
      'update_blog_title': 'Edit Blog',
      'blog_title_label': 'Blog Title',
      'blog_content_label': 'Blog Content',
      'blog_category_label': 'Category',
      'blog_status_label': 'Status',
      'blog_thumbnail_label': 'Thumbnail',
      'select_thumbnail': 'Select Thumbnail',
      'change_thumbnail': 'Change Image',
      'remove_thumbnail': 'Remove Image',
      'thumbnail_error': 'Selected image is invalid or unsupported format.',
      'title_required': 'Please enter title',
      'title_length_error': 'Title must be between 10 and 500 characters',
      'content_required': 'Content cannot be empty',
      'category_required': 'Please select a category',
      'status_required': 'Please select status',
      'create_blog_success': 'Blog created successfully!',
      'update_blog_success': 'Blog updated successfully!',
      'create_blog_failed': 'Failed to create blog.',
      'update_blog_failed': 'Failed to update blog.',
      'confirm_delete_blog_title': 'Confirm Delete',
      'confirm_delete_blog_message': 'Are you sure you want to delete blog:',
      'delete_blog_success': 'Blog deleted successfully!',
      'delete_blog_failed': 'Delete failed. Check password or try again.',
      'enter_password_confirm': 'Enter your password',
      'password_confirm_hint': 'Password to confirm',
      'manage_categories': 'Manage Categories',
      'create_category': 'Create Category',
      'edit_category': 'Edit Category',
      'add_new_category': 'Add New Category',
      'no_categories': 'No categories found',
      'confirm_delete_category':
          'Are you sure you want to delete this category?',

      'no_categories_yet': 'No categories yet',
      'add_new_category_hint': 'Press "+" button to add new category.',
      'create_category_title': 'Create New Category',
      'update_category_title': 'Update Category',
      'category_name_label': 'Category Name',
      'category_name_hint': 'Ex: Medical News',
      'category_desc_label': 'Description (Optional)',
      'category_desc_hint': 'Short description of category',
      'category_name_required': 'Category name cannot be empty',
      'create_category_success': 'Category created successfully!',
      'update_category_success': 'Category updated successfully!',
      'confirm_delete_category_message':
          'Are you sure you want to delete category:',
      'force_delete_label': 'Force Delete',
      'force_delete_desc':
          'Delete this category even if it is linked to blogs.',
      'delete_category_success': 'Category deleted successfully!',
      'status_draft': 'Draft',
      'status_published': 'Published',
      'status_archived': 'Archived',
      'sort_by': 'Sort by',
      'sort_published_at': 'Published Date',
      'sort_created_at': 'Created Date',
      'sort_updated_at': 'Updated Date',
      'order_label': 'Order',
      'retry': 'Retry',
      'all_categories': 'All Categories',
      'view_blog_details': 'View Details',
      'edit_post': 'Edit Post',
      'delete_post': 'Delete Post',
      'read_time_min': 'min read',
      'author_label': 'Author',
      'views_label': 'views',
      // Doctor Management
      'doctor_management_title': 'Doctor Management',
      'search_doctor_hint': 'Search by name or email',
      'create_doctor_account': 'Create Doctor Account',
      'update_doctor_account': 'Edit Doctor Account',
      'no_doctors_found': 'No doctors found',
      'doctor_role': 'Doctor',
      'gender_label': 'Gender',
      'sort_name': 'Name',
      'sort_email': 'Email',
      'doctor_detail_error': 'Cannot load doctor data',
      'account_info': 'Account Information',
      'professional_profile': 'Professional Profile',
      'no_degree_info': 'No degree info',
      'active_status': 'Active',
      'inactive_status': 'Inactive',
      'offline_status_change_error': 'Cannot change status while offline',
      'review_for': 'Reviews for',
      'no_reviews_yet': 'No reviews yet',
      'view_all_reviews': 'View all reviews',
      'confirm_delete_review': 'Confirm Delete',
      'confirm_delete_review_message':
          'Are you sure you want to delete this review?',
      'delete_review_success': 'Review deleted successfully',
      'delete_review_failed': 'Delete failed',
      'edit_profile_title': 'Edit Profile',
      'main_profile_tab': 'Main Profile',
      'details_tab': 'Details',
      'specialty_tab': 'Specialty',
      'save_profile': 'Save Profile',
      'saving_profile': 'Saving...',
      'offline_save_error': 'Cannot save while offline',
      'portrait_label': 'Portrait',
      'select_avatar': 'Select Avatar',
      'remove_avatar': 'Remove Avatar',
      'select_portrait': 'Select Portrait',
      'remove_portrait': 'Remove Portrait',
      'degree_label': 'Degree (e.g., MD, PhD)',
      'introduction_label': 'Introduction',
      'research_label': 'Scientific Research',
      'position_label': 'Position',
      'experience_label': 'Work Experience',
      'training_label': 'Training Process',
      'awards_label': 'Awards & Achievements',
      'membership_label': 'Association Membership',
      'specialty_label': 'Specialty',
      'work_location_label': 'Work Location',
      'loading_specialties': 'Loading specialties...',
      'loading_locations': 'Loading locations...',
      'update_profile_success': 'Profile updated successfully',
      'unknown_save_error': 'Unknown error while saving',
      'degree_info': 'Degree',
      'email_label': 'Email',
      'phone_label': 'Phone',
      'dob_label': 'Date of Birth',
      'not_updated': 'Not updated',
      'connection_error_loading_cache':
          'Connection error. Trying to load cached data...',
      'error_not_doctor_account': 'Error: Account is not a Doctor.',
      'cache_error_not_doctor': 'Cache error: Account is not a Doctor.',
      'account_info_title': 'Account Information',
      'unable_load_doctor_details': 'Unable to load doctor profile details.',
      'user_profile_not_found': 'User profile not found.',
      'profile_error': 'Profile Error',
      'unknown_error_occurred': 'Unknown error occurred',
      // Specialty Module
      'specialty_management_title': 'Specialty Management',
      'search_specialty_hint': 'Search specialty',
      'create_specialty_title': 'Create New Specialty',
      'update_specialty_title': 'Update Specialty',
      'no_specialties_found': 'No specialties found',
      'no_specialties_yet': 'No specialties yet',
      'add_new_specialty_hint': 'Press "+" button to add new specialty.',
      'specialty_name_label': 'Specialty Name',
      'specialty_desc_label': 'Description',
      'specialty_icon_label': 'Specialty Icon',
      'specialty_name_required': 'Specialty name is required',
      'create_specialty_success': 'Specialty created successfully',
      'update_specialty_success': 'Specialty updated successfully',
      'create_specialty_failed': 'Failed to create specialty',
      'update_specialty_failed': 'Failed to update specialty',
      'confirm_delete_specialty_title': 'Confirm Delete',
      'confirm_delete_specialty_message':
          'Are you sure you want to delete specialty',
      'delete_specialty_success': 'Specialty deleted successfully',
      'delete_specialty_failed': 'Failed to delete specialty',
      'info_section_count': 'Info sections count: ',
      'create_info_section_title': 'Create Info Section',
      'update_info_section_title': 'Update Info Section',
      'info_section_name_label': 'Section Name',
      'info_section_content_label': 'Content',
      'info_section_name_required': 'Section name is required',
      'info_section_content_required': 'Content is required',
      'create_info_section_success': 'Info section created successfully',
      'update_info_section_success': 'Info section updated successfully',
      'confirm_delete_info_section_message':
          'Are you sure you want to delete info section',
      'delete_info_section_success': 'Info section deleted successfully',
      'no_info_sections_yet': 'No info sections yet',
      'add_new_info_section_hint': 'Press "+" button to add new info section.',
      'view_more': 'View more ...',
      'view_less': '... View less',
      'specialty_name_length_error':
          'Name must be between 10 and 200 characters',
      'specialty_desc_length_error':
          'Description must be between 10 and 1000 characters',
      'info_section_name_hint': 'Enter clear title...',
      'info_section_name_length_error':
          'Name must be between 10 and 200 characters',
      'create_btn': 'Create',
      'update_btn': 'Update',
      // Location Work Management
      'location_management_title': 'Work Location Management',
      'search_location_hint': 'Search by name or address',
      'add_location_btn': 'Add Work Location',
      'offline_add_error': 'Cannot add while offline',
      'update_status_success': 'Status updated successfully!',
      'update_status_failed': 'Status update failed.',
      'add_first_location_hint': 'Start by adding your first work location',
      'add_first_location_btn': 'Add First Location',
      'loading_data': 'Loading data...',
      'create_location_title': 'Create Work Location',
      'update_location_title': 'Update Work Location',
      'location_name_label': 'Location Name',
      'location_name_required': 'Please enter location name',
      'location_name_length_error':
          'Name must be between 10 and 200 characters',
      'address_label': 'Address',
      'address_required': 'Please enter address',
      'phone_required': 'Please enter phone number',
      'phone_invalid': 'Invalid phone number',
      'timezone_label': 'Timezone',
      'timezone_required': 'Please select timezone',
      'updating': 'Updating...',
      'creating': 'Creating...',
      'update_location_btn': 'Update Location',
      'create_location_btn': 'Create Location',
      'save_location_failed': 'Failed to save location. Please try again.',
      'confirm_delete_location_message':
          'Are you sure you want to delete location',
      'delete_location_success': 'Location deleted successfully!',
      'delete_location_failed': 'Failed to delete location.',
      'prev_page': 'Previous',
      'next_page': 'Next',
      'page_info': 'Page',
      'google_map_url_label': 'Google Map URL',
      'generate_map_url_tooltip': 'Generate from Address',
      'open_map_tooltip': 'Open in Maps',
      'invalid_url_error': 'Invalid URL',
      'address_required_for_map_error':
          'Address is required to generate map URL',
      'offline_error': 'You are offline. Data may be outdated.',
      'no_offline_data': 'No offline data available',
      'fetch_failed': 'Failed to load data',

      // Question Management
      'question_management_title': 'Question Management',
      'search_question_hint': 'Search by title, content...',
      'filter_sort_title': 'Filter & Sort',
      'all_statuses': 'All Statuses',
      'status_pending': 'Pending',
      'status_answered': 'Answered',
      'status_closed': 'Closed',
      'sort_title': 'Title',
      'sort_asc': 'Ascending',
      'sort_desc': 'Descending',
      'no_questions_found': 'No questions found',
      'no_questions_yet': 'No questions yet',
      'no_questions_hint':
          'Try searching with different keywords or clear filters.',
      'no_questions_system_hint':
          'There are no questions in the system currently.',
      'reload_list': 'Reload list',
      'confirm_delete_answer_message':
          'Are you sure you want to delete this answer?',
      'delete_answer_success': 'Answer deleted successfully',
      'delete_answer_failed': 'Failed to delete answer',
      'answer_approved_success': 'Answer approved successfully',
      'answer_approved_failed': 'Failed to approve answer',
      'submit_answer_title': 'Submit Answer',
      'enter_answer_hint': 'Enter your answer...',
      'submit': 'Submit',
      'answer_submitted_success': 'Answer submitted successfully',
      'answer_submitted_failed': 'Failed to submit answer',
      'edit_answer_title': 'Edit Answer',
      'answer_updated_success': 'Answer updated successfully',
      'answer_updated_failed': 'Failed to update answer',
      'edit_question_title': 'Edit Question',
      'select_specialty_hint': 'Select specialty',
      'select_status_hint': 'Select status',
      'question_updated_success': 'Question updated successfully',
      'question_detail_title': 'Question Detail',
      'status_prefix': 'Status: ',
      'answers_section_title': 'Answers',
      'no_answers_yet': 'No answers yet',
      'approved_label': 'APPROVED',
      'doctor_id_prefix': 'Doctor ID: ',
      'approve': 'Approve',
      'confirm_delete_question_message':
          'Are you sure you want to delete question',
      'action_irreversible': 'This action cannot be undone.',
      'password_min_length_1': 'Password must be at least 1 character',
      'delete_question_success': 'Question deleted successfully!',
      // Change Password
      'change_password_success': 'Password changed successfully!',
      'change_password_failed':
          'Password change failed. Please check your current password.',
      'change_password_instruction':
          'Please enter your current password and new password.',
      'current_password': 'Current Password',
      'current_password_required': 'Please enter current password',
      'new_password': 'New Password',
      'confirm_new_password': 'Confirm New Password',
      'confirm_new_password_required': 'Please confirm new password',
      'password_mismatch': 'Passwords do not match',
      // Profile
      'role': 'Role',
      'offline_load_error': 'Connection error. Trying to load cached data...',
      'load_profile_error': 'Error loading profile: ',
      'offline_no_cache': 'You are offline and no cached data available.',
      'cannot_load_profile': 'Cannot load personal profile.',
      'no_profile_data': 'No profile data.',

      // Office Hours
      'office_hours_title': 'Manage Office Hours',
      'add_office_hour': 'Add Office Hour',
      'create_office_hour_success': 'Office hour created successfully',
      'delete_office_hour_confirm_title': 'Confirm Delete',
      'delete_office_hour_confirm_message':
          'Are you sure you want to delete this office hour?',
      'delete_office_hour_success': 'Deleted successfully',
      'global_hours_label': 'Global Hours',
      'global_hours_subtitle': 'Apply to all locations (no doctor selected)',
      'doctor_optional': 'Doctor (Optional)',
      'no_doctor_selected': 'No doctor selected',
      'location_optional': 'Location (Optional)',
      'day_of_week': 'Day of Week',
      'start_time': 'Start Time',
      'end_time': 'End Time',
      'create_office_hour_btn': 'Create Office Hour',
      'no_office_hours_found': 'No office hours found',
      'add_new_office_hour_hint': 'Press "+" button to add new office hour.',
      'loading_data_error': 'Error loading data: ',
      'monday': 'Monday',
      'tuesday': 'Tuesday',
      'wednesday': 'Wednesday',
      'thursday': 'Thursday',
      'friday': 'Friday',
      'saturday': 'Saturday',
      'sunday': 'Sunday',
      'doctor_at_loc_tab': 'Doctor @ Loc',
      'doctor_only_tab': 'Doctor Only',
      'location_only_tab': 'Location Only',
      'global_tab': 'Global',
      'doctor_loc_badge': 'Dr. & Loc',
      'doctor_badge': 'Doctor',
      'location_badge': 'Location',
      'am': 'AM',
      'pm': 'PM',
      'global_badge': 'Global',
      'rule_type_label': 'Rule Type',
      'rule_type_specific': 'Specific (Doctor @ Location)',
      'rule_type_doctor_default': 'Doctor Default',
      'rule_type_location_default': 'Location Default',
      'rule_type_global_default': 'Global System Default',
      'priority_highest': 'Highest',
      'priority_medium': 'Medium',
      'priority_low': 'Low',
      'priority_lowest': 'Lowest',
      // Permission Management
      'permissions': 'Permissions',
      'resource': 'Resource',
      'action': 'Action',
      'allow': 'Allow',
      'deny': 'Deny',
      'grant': 'Grant',
      'revoke': 'Revoke',
      'manage_permission_groups': 'Manage Permission Groups',
      'permission_group_detail': 'Permission Group Detail',
      'user_permissions': 'User Permissions',
      'direct_permissions': 'Direct Permissions',
      'roles_groups': 'Roles (Groups)',
      'manage_permissions': 'Manage Permissions',
      'manage_groups': 'Manage Groups',
      'select_permissions': 'Select Permissions',
      'no_direct_permissions': 'No direct permissions assigned',
      'user_no_groups': 'User belongs to no groups',
      'group_update_success': 'Group updated successfully',
      'group_delete_confirm': 'Are you sure you want to delete this group?',
      'group_delete_success': 'Group deleted successfully',
      'resource_doctors': 'Doctors',
      'resource_patients': 'Patients',
      'resource_appointments': 'Appointments',
      'resource_medical_records': 'Medical Records',
      'resource_prescriptions': 'Prescriptions',
      'resource_services': 'Services',
      'resource_staffs': 'Staffs',
      'resource_permissions': 'Permissions',
      'action_create': 'Create',
      'action_read': 'Read',
      'action_update': 'Update',
      'action_delete': 'Delete',
      'action_manage': 'Manage',
      'permission_management_title': 'Permission & Security',
      'group_tab': 'Permission Groups',
      'user_tab': 'Users',
      'create_group_title': 'Create New Group',
      'group_name_label': 'Group Name',
      'group_desc_label': 'Description',
      'create_success': 'Created successfully',
      'user_role': 'Role',
      'my_permissions_title': 'My Permissions',
      'statistics_tab': 'Statistics',
      'no_statistics_available': 'No statistics available',
      'total_permissions': 'Total Permissions',
      'total_groups': 'Total Groups',
      'assigned_to_users': 'Assigned to Users',
      'assigned_to_groups': 'Assigned to Groups',
      'most_used_permissions': 'Most Used Permissions',
      'largest_groups': 'Largest Groups',
      'error_loading_permissions': 'Error loading permissions',
      'no_permissions_found': 'No permissions found',
      'no_conditions': 'No conditions',
      'fetch_users_error': 'Failed to load users list.',
      'fetch_groups_error': 'Failed to load permission groups.',
      'create_group_error': 'Failed to create permission group.',
      'update_group_error': 'Failed to update permission group.',
      'delete_group_error': 'Failed to delete permission group.',
      'fetch_permissions_error': 'Failed to load permissions.',
      'update_permissions_error': 'Failed to update permissions.',
      'fetch_stats_error': 'Failed to load statistics.',
      'assign_permission_success': 'Permissions assigned successfully',
      'assign_permission_failed': 'Failed to assign permissions',
      'revoke_permission_failed': 'Failed to revoke permissions',
      'search_users_hint': 'Search users...',
      'danger_zone': 'Danger Zone',
      'delete_group_warning':
          'Deleting this group is irreversible and will remove all associated permissions.',
      'error_default_group_update': 'Cannot modify default system group.',
      'search_groups_hint': 'Search groups...',
      'uploading_icon_wait': 'Uploading icon, please wait...',
      'no_page_route': 'No page route provided',
      'add_item_hint': 'Add {item}...',

      'edit_info_title': 'Edit Information',
      'confirm_delete_role_message': 'Are you sure you want to delete ',

      'delete_role_success': 'Delete {role} successfully!',
      'delete_failed_retry': 'Delete failed. Check password or try again.',

      'enter_pass_prompt': 'Please enter password',
      'password_min_len': 'Password must be at least 6 characters',
      'password_max_len': 'Password must not exceed 50 characters',
      'error_occurred_retry_msg': 'An error occurred. Please try again.',
      'update_profile_succ': 'Update information successfully!',
      'enter_super_admin_pass': 'Enter Super Admin password',
      'password_hint_range': 'Password from 6-50 characters',
    },
    'vi': {
      'login': 'Đăng nhập',
      'email': 'Email',
      'password': 'Mật khẩu',
      'forgot_password': 'Quên mật khẩu?',
      'login_button': 'Đăng Nhập',
      'app_slogan': 'Ứng dụng quản lý dành cho bác sĩ',
      'error': 'Lỗi',
      'ok': 'OK',
      'no_data': 'Không có dữ liệu',
      'select': 'Chọn',
      'unselected': 'Chưa chọn',
      'add': 'Thêm',
      'login_failed':
          'Đăng nhập thất bại. Vui lòng kiểm tra email và mật khẩu.',
      'email_required': 'Vui lòng nhập email',
      'email_invalid': 'Email không đúng định dạng',
      'password_required': 'Vui lòng nhập mật khẩu',
      'password_invalid':
          'Mật khẩu tối thiểu 8 ký tự, có ít nhất 1 chữ cái và 1 số',
      'forgot_password_title': 'Quên mật khẩu',
      'reset_email_sent_message':
          'Nếu tài khoản tồn tại, mã đặt lại đã được gửi.',
      'reset_email_send_failed':
          'Gửi email đặt lại thất bại. Vui lòng thử lại.',
      'enter_email_instruction': 'Nhập email của bạn để nhận mã đặt lại.',
      'verify_code_title': 'Xác thực mã',
      'verify_code_instruction': 'Nhập mã 6 chữ số đã gửi tới ',
      'otp_code_label': 'Mã OTP',
      'otp_required_error': 'Vui lòng nhập mã',
      'otp_length_error': 'Mã phải có 6 chữ số',
      'verify_code_success': 'Xác thực mã thành công.',
      'verify_code_invalid': 'Mã không hợp lệ hoặc đã hết hạn.',
      'verifying': 'Đang xác thực...',
      'verify': 'Xác thực',
      'reset_password_page_title': 'Đặt lại mật khẩu',
      'reset_password_success':
          'Đặt lại mật khẩu thành công. Vui lòng đăng nhập.',
      'reset_password_failed': 'Đặt lại mật khẩu thất bại. Vui lòng thử lại.',
      'password_required_error': 'Vui lòng nhập mật khẩu mới',
      'confirm_password_required_error': 'Vui lòng xác nhận mật khẩu',
      'settings': 'Cài đặt',
      'language': 'Ngôn ngữ',
      'english': 'Tiếng Anh',
      'vietnamese': 'Tiếng Việt',
      'logout': 'Đăng xuất',
      'change_password': 'Đổi mật khẩu',
      'profile': 'Hồ sơ',
      'theme': 'Giao diện',
      'dark_mode': 'Chế độ tối',
      'light_mode': 'Chế độ sáng',
      'system_mode': 'Chế độ hệ thống',
      'personal_information': 'Thông tin cá nhân',
      'specialty_management': 'Quản lý chuyên khoa',
      'location_management': 'Quản lý địa điểm khám',
      'office_hours_management': 'Quản lý giờ làm việc',
      'patient_management': 'Quản lý bệnh nhân',
      'permission_management': 'Quản lý phân quyền',
      'account_management': 'Quản lý tài khoản',
      'logout_confirmation_title': 'Xác nhận đăng xuất',
      'logout_confirmation_message':
          'Bạn có chắc chắn muốn đăng xuất khỏi tài khoản này không?',
      'cancel': 'Hủy',
      'logout_failed': 'Đăng xuất thất bại, vui lòng thử lại!',
      'schedule_management': 'QUẢN LÝ LỊCH TRÌNH',
      'answer_questions': 'TRẢ LỜI CÂU HỎI',
      'patient_reviews': 'CẢM NHẬN BỆNH NHÂN',
      'profile_management': 'QUẢN LÝ HỒ SƠ',
      'appointment_management': 'QUẢN LÝ LỊCH KHÁM',
      'doctor_management': 'QUẢN LÝ BÁC SĨ',
      // Blog Module (VI)
      'manage_categories': 'Quản lý danh mục',
      'create_category': 'Tạo danh mục',
      'edit_category': 'Chỉnh sửa danh mục',
      'add_new_category': 'Thêm danh mục mới',
      'no_categories': 'Không tìm thấy danh mục nào',
      'confirm_delete_category': 'Bạn có chắc chắn muốn xóa danh mục này?',

      'admin_account_management': 'QUẢN LÝ TÀI KHOẢN ADMIN',
      'logged_in_as_admin': 'Bạn đang đăng nhập với tư cách là admin',
      'logged_in_as_super_admin':
          'Bạn đang đăng nhập với tư cách là super admin',
      'error_load_doctor_profile': 'Không thể tải hồ sơ bác sĩ.',
      'error_load_specialty_profile': 'Không thể tải hồ sơ chuyên môn.',
      'error_occurred': 'Đã xảy ra lỗi: ',
      // Appointment Module
      'appointments_title': 'Lịch hẹn',
      'loading_list': 'Đang tải danh sách...',
      'select_doctor': 'Chọn bác sĩ',
      'step_patient': 'Bệnh nhân',
      'step_service': 'Dịch vụ',
      'step_schedule': 'Lịch hẹn',
      'step_details': 'Chi tiết',
      'step_confirm': 'Xác nhận',
      'create_appointment_title': 'Tạo lịch hẹn mới',
      'back': 'Quay lại',
      'continue_step': 'Tiếp tục',
      'confirm_booking': 'Xác nhận đặt lịch',
      'error_select_patient': 'Vui lòng chọn bệnh nhân',
      'error_select_service_info': 'Vui lòng chọn đầy đủ thông tin dịch vụ',
      'error_select_datetime': 'Vui lòng chọn ngày và giờ hẹn',
      'search_select_patient': 'Tìm kiếm và chọn bệnh nhân',
      'search_patient_hint': 'Nhập tên, email hoặc SĐT',
      'no_email': 'Không có email',
      'no_phone': 'Không có SĐT',
      'service_info': 'Thông tin dịch vụ',
      'location': 'Địa điểm',
      'specialty': 'Chuyên khoa',
      'doctor': 'Bác sĩ',
      'select_time': 'Chọn thời gian',
      'selected_slot': 'Đã chọn: ',
      'details_info': 'Thông tin chi tiết',
      'reason_for_visit': 'Lý do khám',
      'additional_notes': 'Ghi chú thêm',
      'examination_price': 'Giá khám',
      'currency': 'Tiền tệ',
      'confirm_info': 'Xác nhận thông tin',
      'time': 'Thời gian',
      'reason': 'Lý do',
      'notes': 'Ghi chú',
      'price': 'Giá',
      'none': 'Không có',
      'not_entered': 'Chưa nhập',
      'booking_success': 'Đặt lịch thành công!',
      'update_appointment_title': 'Cập nhật lịch hẹn',
      'status': 'Trạng thái',
      'price_vnd': 'Giá tiền (VND)',
      'error_invalid_number': 'Vui lòng nhập số hợp lệ',
      'save': 'Lưu',
      'update_success': 'Cập nhật thành công',
      'error_occurred_short': 'Có lỗi xảy ra',
      'cancel_appointment_title': 'Hủy lịch hẹn',
      'cancel_appointment_confirm':
          'Bạn có chắc chắn muốn hủy lịch hẹn này không?',
      'cancel_reason_required': 'Lý do hủy *',
      'error_enter_reason': 'Vui lòng nhập lý do',
      'close': 'Đóng',
      'cancel_success': 'Đã hủy lịch hẹn',
      'reschedule_appointment_title': 'Dời lịch hẹn',
      'confirm_appointment_title': 'Xác nhận lịch hẹn',
      'confirm_appointment_message':
          'Bạn có chắc chắn muốn xác nhận lịch hẹn này?',
      'confirm': 'Xác nhận',
      'confirm_success': 'Đã xác nhận lịch hẹn',
      'confirm_reschedule_title': 'Xác nhận dời lịch',
      'reschedule_confirm_message': 'Dời sang ',
      'agree': 'Đồng ý',
      'reschedule_success': 'Dời lịch thành công',
      'reschedule': 'Dời lịch',
      'status_booked': 'Đã đặt',
      'status_confirmed': 'Đã xác nhận',
      'status_completed': 'Hoàn thành',
      'status_cancelled': 'Đã hủy',
      'status_rescheduled': 'Đã dời',
      'patient': 'Bệnh nhân',
      'date_label': 'Ngày',
      'appointment_filter_title': 'Bộ lọc lịch hẹn',
      'reset': 'Đặt lại',
      'apply': 'Áp dụng',
      'all_doctors': 'Tất cả bác sĩ',
      'work_location': 'Cơ sở làm việc',
      'all_locations': 'Tất cả cơ sở',
      'all_specialties': 'Tất cả chuyên khoa',
      'calendar_settings_title': 'Cài đặt lịch',
      'display_hours': 'Giờ hiển thị',
      'card_appearance': 'Giao diện thẻ',
      'background_color': 'Màu nền',
      'dot': 'Chấm tròn',
      'mixed': 'Kết hợp',
      'working_days': 'Ngày làm việc',
      'save_changes': 'Lưu thay đổi',
      'mon': 'T2',
      'tue': 'T3',
      'wed': 'T4',
      'thu': 'T5',
      'fri': 'T6',
      'sat': 'T7',
      'sun': 'CN',
      // Patient Module
      'patient_management_title': 'Quản lý Bệnh nhân',
      'offline_create_patient_error':
          'Không thể tạo bệnh nhân khi đang offline',
      'search_patient': 'Tìm kiếm bệnh nhân',
      'offline_banner': 'Bạn đang offline. Dữ liệu có thể đã cũ.',
      'no_patients_found': 'Không tìm thấy bệnh nhân nào.',
      'offline_edit_error': 'Không thể sửa khi đang offline',
      'edit': 'Sửa',
      'offline_delete_error': 'Không thể xóa/khôi phục khi đang offline',
      'restore': 'Khôi phục',
      'delete': 'Xóa',
      'deleted': 'Đã xóa',
      'create_patient_success': 'Tạo bệnh nhân thành công',
      'create_patient_failed': 'Tạo bệnh nhân thất bại',
      'create_patient_title': 'Tạo Bệnh nhân mới',
      'update_patient_success': 'Cập nhật bệnh nhân thành công',
      'update_patient_failed': 'Cập nhật bệnh nhân thất bại',
      'update_patient_title': 'Cập nhật Bệnh nhân',
      'fetch_patients_error': 'Lỗi tải danh sách bệnh nhân.',
      'create_patient_error': 'Lỗi tạo bệnh nhân.',
      'update_patient_error': 'Lỗi cập nhật bệnh nhân.',
      'delete_patient_error': 'Lỗi xóa bệnh nhân.',
      'restore_patient_error': 'Lỗi khôi phục bệnh nhân.',
      'confirm_delete_patient_title': 'Xóa bệnh nhân',
      'confirm_delete_patient_message':
          'Bạn có chắc chắn muốn xóa bệnh nhân này?',
      'confirm_delete_title': 'Xác nhận Xóa',
      'confirm_delete_patient_named': 'Bạn có chắc chắn muốn xóa bệnh nhân ',
      'full_name': 'Họ và tên',
      'error_enter_full_name': 'Vui lòng nhập họ và tên',
      'phone_number': 'Số điện thoại',
      'date_of_birth': 'Ngày sinh',
      'gender': 'Giới tính',
      'unknown': 'Không xác định',
      'male': 'Nam',
      'female': 'Nữ',
      'contact_address': 'Địa chỉ liên lạc',
      'address': 'Địa chỉ',
      'district': 'Quận/Huyện',
      'province': 'Tỉnh/Thành phố',
      'years_old_suffix': 'tuổi',
      'create_new': 'Tạo mới',
      'update': 'Cập nhật',
      // Admin Management Module
      'admin_management_title': 'Quản lý Admin',
      'search_by_name_email': 'Tìm kiếm theo tên hoặc email',
      'create_admin_account': 'Tạo tài khoản admin',
      'filter_sort': 'Bộ lọc & Sắp xếp',
      'all': 'Tất cả',
      'sort': 'Sắp xếp',
      'created_date': 'Ngày tạo',
      'name': 'Tên',
      'ascending': 'Tăng dần',
      'descending': 'Giảm dần',
      'no_admins_found': 'Không có admin nào',
      'edit_admin_account': 'Chỉnh sửa tài khoản admin',
      'confirm_delete_staff_message': 'Bạn có chắc chắn muốn xóa ',
      'password_min_length': 'Mật khẩu phải có ít nhất 6 ký tự',
      'password_max_length': 'Mật khẩu không được vượt quá 50 ký tự',
      'delete_success': 'Xóa thành công',
      'delete_failed': 'Xóa thất bại. Kiểm tra mật khẩu hoặc thử lại.',
      'error_occurred_retry': 'Có lỗi xảy ra. Vui lòng thử lại.',
      'password_length_error': 'Mật khẩu phải từ 6 đến 50 ký tự',
      'incorrect_password': 'Mật khẩu không chính xác',
      'forbidden_action': 'Bạn không có quyền thực hiện hành động này',
      'too_many_requests': 'Quá nhiều yêu cầu. Vui lòng thử lại sau!',
      'enter_super_admin_password': 'Nhập mật khẩu Super Admin',
      'password_hint': 'Mật khẩu từ 6-50 ký tự',
      'processing': 'Đang xử lý...',
      'new_password_optional': 'Mật khẩu mới (để trống nếu không đổi)',
      'password_complexity_error': 'Mật khẩu tối thiểu 8 ký tự, có chữ và số',
      'phone_number_invalid': 'Số điện thoại phải là 10 chữ số',
      'date_of_birth_format': 'Ngày sinh (dd/mm/yyyy)',
      'date_of_birth_required': 'Vui lòng chọn ngày sinh',
      'create': 'Tạo',
      'failed': 'thất bại',
      // Blog Module
      'blog_management_title': 'Quản lý Blog',
      'search_blog_hint': 'Tìm kiếm theo tiêu đề',
      'no_blogs_found': 'Không tìm thấy bài viết',
      'no_blogs_yet': 'Chưa có bài viết nào',
      'add_new_blog_hint': 'Nhấn nút "+" ở góc dưới để thêm bài viết mới.',
      'try_search_again': 'Hãy thử tìm kiếm với từ khóa khác hoặc xóa bộ lọc.',
      'create_blog_title': 'Tạo bài viết mới',
      'update_blog_title': 'Chỉnh sửa bài viết',
      'blog_title_label': 'Tiêu đề bài viết',
      'blog_content_label': 'Nội dung bài viết',
      'blog_category_label': 'Danh mục',
      'blog_status_label': 'Trạng thái',
      'blog_thumbnail_label': 'Ảnh bìa (Thumbnail)',
      'select_thumbnail': 'Chọn ảnh bìa',
      'change_thumbnail': 'Đổi ảnh',
      'remove_thumbnail': 'Xóa ảnh',
      'thumbnail_error':
          'Ảnh đã chọn bị lỗi hoặc có định dạng không được hỗ trợ.',
      'title_required': 'Vui lòng nhập tiêu đề',
      'title_length_error': 'Tiêu đề phải từ 10 đến 500 ký tự',
      'content_required': 'Nội dung không được để trống',
      'category_required': 'Vui lòng chọn danh mục',
      'status_required': 'Vui lòng chọn trạng thái',
      'create_blog_success': 'Tạo bài viết thành công!',
      'update_blog_success': 'Cập nhật bài viết thành công!',
      'create_blog_failed': 'Tạo bài viết thất bại.',
      'update_blog_failed': 'Cập nhật bài viết thất bại.',
      'confirm_delete_blog_title': 'Xác nhận xóa',
      'confirm_delete_blog_message': 'Bạn có chắc chắn muốn xóa bài viết:',
      'delete_blog_success': 'Xóa bài viết thành công!',
      'delete_blog_failed': 'Xóa thất bại. Kiểm tra mật khẩu hoặc thử lại.',
      'enter_password_confirm': 'Nhập mật khẩu của bạn',
      'password_confirm_hint': 'Mật khẩu để xác nhận',
      'manage_blog_categories': 'Quản lý Danh mục Blog',
      'no_categories_yet': 'Chưa có danh mục nào',
      'add_new_category_hint': 'Nhấn nút "+" để thêm danh mục mới.',
      'view_blog_details': 'Xem chi tiết',
      'edit_post': 'Chỉnh sửa',
      'delete_post': 'Xóa bài viết',
      'read_time_min': 'phút đọc',
      'author_label': 'Tác giả',
      'views_label': 'lượt xem',
      'my_permissions_title': 'Quyền của tôi',
      'statistics_tab': 'Thống kê',
      'no_statistics_available': 'Không có dữ liệu thống kê',
      'total_permissions': 'Tổng số quyền',
      'total_groups': 'Tổng số nhóm',
      'assigned_to_users': 'Đã gán cho người dùng',
      'assigned_to_groups': 'Đã gán cho nhóm',
      'most_used_permissions': 'Quyền được dùng nhiều nhất',
      'largest_groups': 'Nhóm lớn nhất',
      'error_loading_permissions': 'Lỗi tải quyền hạn',
      'no_permissions_found': 'Không tìm thấy quyền hạn nào',
      'no_conditions': 'Không có điều kiện',
      'create_category_title': 'Tạo Danh mục mới',
      'update_category_title': 'Cập nhật Danh mục',
      'category_name_label': 'Tên danh mục',
      'category_name_hint': 'VD: Tin tức y tế',
      'category_desc_label': 'Mô tả (Không bắt buộc)',
      'category_desc_hint': 'Mô tả ngắn về danh mục',
      'category_name_required': 'Tên danh mục không được để trống',
      'create_category_success': 'Tạo danh mục thành công!',
      'update_category_success': 'Cập nhật danh mục thành công!',
      'confirm_delete_category_message': 'Bạn có chắc chắn muốn xóa danh mục:',
      'force_delete_label': 'Buộc xóa (Force Delete)',
      'force_delete_desc':
          'Xóa danh mục này ngay cả khi nó đang được liên kết với các bài viết.',
      'delete_category_success': 'Xóa danh mục thành công!',
      'status_draft': 'Bản nháp',
      'status_published': 'Xuất bản',
      'status_archived': 'Lưu trữ',
      'sort_by': 'Sắp xếp theo',
      'sort_published_at': 'Ngày xuất bản',
      'sort_created_at': 'Ngày tạo',
      'sort_updated_at': 'Ngày cập nhật',
      'order_label': 'Thứ tự',
      'retry': 'Thử lại',
      'all_categories': 'Tất cả danh mục',
      // Doctor Management
      'doctor_management_title': 'Quản lý Bác sĩ',
      'search_doctor_hint': 'Tìm kiếm theo tên hoặc email',
      'create_doctor_account': 'Tạo tài khoản bác sĩ',
      'update_doctor_account': 'Chỉnh sửa tài khoản bác sĩ',
      'no_doctors_found': 'Không có bác sĩ nào',
      'doctor_role': 'Bác sĩ',
      'gender_label': 'Giới tính',
      'sort_name': 'Tên',
      'sort_email': 'Email',
      'doctor_detail_error': 'Không thể tải dữ liệu bác sĩ',
      'account_info': 'Thông tin tài khoản',
      'professional_profile': 'Hồ sơ chuyên môn',
      'no_degree_info': 'Chưa có thông tin học vị',
      'active_status': 'Đang hoạt động',
      'inactive_status': 'Tạm ngưng',
      'offline_status_change_error':
          'Không thể thay đổi trạng thái khi offline',
      'review_for': 'Đánh giá cho',
      'no_reviews_yet': 'Bác sĩ này chưa có đánh giá',
      'view_all_reviews': 'Xem tất cả đánh giá',
      'confirm_delete_review': 'Xác nhận xóa',
      'confirm_delete_review_message':
          'Bạn có chắc chắn muốn xóa đánh giá này?',
      'delete_review_success': 'Xóa đánh giá thành công',
      'delete_review_failed': 'Xóa thất bại',
      // Permission Management
      'permissions': 'Quyền hạn',
      'resource': 'Tài nguyên',
      'action': 'Hành động',
      'allow': 'Cho phép',
      'deny': 'Từ chối',
      'grant': 'Cấp quyền',
      'revoke': 'Thu hồi',
      'manage_permission_groups': 'Quản lý Nhóm quyền',
      'permission_group_detail': 'Chi tiết Nhóm quyền',
      'user_permissions': 'Phân quyền Người dùng',
      'direct_permissions': 'Quyền trực tiếp',
      'roles_groups': 'Vai trò (Nhóm)',
      'manage_permissions': 'Cấu hình quyền',
      'manage_groups': 'Quản lý Nhóm',
      'select_permissions': 'Chọn quyền',
      'no_direct_permissions': 'Không có quyền trực tiếp nào',
      'user_no_groups': 'Người dùng chưa thuộc nhóm nào',
      'group_update_success': 'Cập nhật nhóm thành công',
      'group_delete_confirm': 'Bạn có chắc chắn muốn xóa nhóm này?',
      'group_delete_success': 'Xóa nhóm thành công',
      'resource_doctors': 'Bác sĩ',
      'resource_patients': 'Bệnh nhân',
      'resource_appointments': 'Lịch hẹn',
      'resource_medical_records': 'Hồ sơ bệnh án',
      'resource_prescriptions': 'Đơn thuốc',
      'resource_user': 'Người dùng',
      'resource_group': 'Nhóm quyền',
      'resource_permission': 'Phân quyền',
      'danger_zone': 'Vùng nguy hiểm',
      'delete_group_warning':
          'Xóa nhóm này sẽ xóa vĩnh viễn và thu hồi quyền từ tất cả người dùng được gán.',
      'action_create': 'Tạo',
      'action_read': 'Xem',
      'action_update': 'Cập nhật',
      'action_delete': 'Xóa',
      'action_manage': 'Quản lý',
      'permission_management_title': 'Phân quyền & Bảo mật',
      'group_tab': 'Nhóm quyền',
      'user_tab': 'Người dùng',
      'create_group_title': 'Tạo nhóm quyền mới',
      'group_name_label': 'Tên nhóm',
      'group_desc_label': 'Mô tả',
      'create_success': 'Tạo thành công',
      'user_role': 'Vai trò',
      'edit_profile_title': 'Chỉnh sửa hồ sơ',
      'main_profile_tab': 'Hồ sơ chính',
      'details_tab': 'Chi tiết',
      'specialty_tab': 'Chuyên môn',
      'save_profile': 'Lưu hồ sơ',
      'saving_profile': 'Đang lưu...',
      'offline_save_error': 'Không thể lưu khi offline',
      'portrait_label': 'Ảnh bìa (Portrait)',
      'select_avatar': 'Chọn ảnh đại diện',
      'remove_avatar': 'Xóa ảnh đại diện',
      'select_portrait': 'Chọn ảnh bìa mới',
      'remove_portrait': 'Xóa ảnh bìa',
      'degree_label': 'Học vị (VD: ThS.BS)',
      'introduction_label': 'Giới thiệu',
      'research_label': 'Nghiên cứu khoa học',
      'position_label': 'Chức vụ',
      'experience_label': 'Kinh nghiệm làm việc',
      'training_label': 'Quá trình đào tạo',
      'awards_label': 'Giải thưởng & Thành tích',
      'membership_label': 'Thành viên hiệp hội',
      'specialty_label': 'Chuyên khoa',
      'work_location_label': 'Nơi công tác',
      'loading_specialties': 'Đang tải danh sách chuyên khoa...',
      'loading_locations': 'Đang tải danh sách địa điểm...',
      'update_profile_success': 'Cập nhật hồ sơ thành công',
      'unknown_save_error': 'Lỗi không xác định khi lưu',
      'degree_info': 'Học vị',
      'email_label': 'Email',
      'phone_label': 'Số điện thoại',
      'dob_label': 'Ngày sinh',
      'not_updated': 'Chưa cập nhật',
      'connection_error_loading_cache':
          'Lỗi kết nối. Đang thử tải dữ liệu cache...',
      'error_not_doctor_account': 'Lỗi: Tài khoản không phải là Bác sĩ.',
      'cache_error_not_doctor': 'Lỗi cache: Tài khoản không phải là Bác sĩ.',
      'account_info_title': 'Thông tin tài khoản',
      'unable_load_doctor_details': 'Không thể tải chi tiết hồ sơ bác sĩ.',
      'user_profile_not_found': 'Không tìm thấy hồ sơ người dùng.',
      'profile_error': 'Lỗi Hồ sơ',
      'unknown_error_occurred': 'Đã xảy ra lỗi không xác định',
      // Specialty Module
      'specialty_management_title': 'Quản lý Chuyên khoa',
      'search_specialty_hint': 'Tìm kiếm chuyên khoa',
      'create_specialty_title': 'Tạo chuyên khoa mới',
      'update_specialty_title': 'Chỉnh sửa chuyên khoa',
      'no_specialties_found': 'Không tìm thấy chuyên khoa',
      'no_specialties_yet': 'Chưa có chuyên khoa nào',
      'add_new_specialty_hint': 'Nhấn nút "Thêm chuyên khoa mới" để bắt đầu.',
      'specialty_name_label': 'Tên chuyên khoa',
      'specialty_desc_label': 'Mô tả',
      'specialty_icon_label': 'Biểu tượng chuyên khoa',
      'specialty_name_required': 'Tên chuyên khoa không được để trống',
      'create_specialty_success': 'Tạo chuyên khoa thành công',
      'update_specialty_success': 'Cập nhật chuyên khoa thành công',
      'create_specialty_failed': 'Tạo chuyên khoa thất bại',
      'update_specialty_failed': 'Cập nhật chuyên khoa thất bại',
      'confirm_delete_specialty_title': 'Xác nhận xóa',
      'confirm_delete_specialty_message':
          'Bạn có chắc chắn muốn xóa chuyên khoa',
      'delete_specialty_success': 'Xóa chuyên khoa thành công',
      'delete_specialty_failed': 'Xóa chuyên khoa thất bại',
      'info_section_count': 'Số phần thông tin: ',
      'create_info_section_title': 'Tạo phần thông tin',
      'update_info_section_title': 'Chỉnh sửa phần thông tin',
      'info_section_name_label': 'Tên phần thông tin',
      'info_section_content_label': 'Nội dung',
      'info_section_name_required': 'Tên phần thông tin không được để trống',
      'info_section_content_required': 'Nội dung không được để trống',
      'create_info_section_success': 'Tạo phần thông tin thành công',
      'update_info_section_success': 'Cập nhật phần thông tin thành công',
      'confirm_delete_info_section_message':
          'Bạn có chắc chắn muốn xóa phần thông tin',
      'delete_info_section_success': 'Xóa phần thông tin thành công',
      'no_info_sections_yet': 'Chưa có phần thông tin nào',
      'add_new_info_section_hint':
          'Nhấn nút + ở góc dưới để thêm thông tin chi tiết cho chuyên khoa này.',
      'view_more': 'Xem thêm ...',
      'view_less': '... Thu gọn',
      'specialty_name_length_error': 'Tên phải từ 10 đến 200 ký tự',
      'specialty_desc_length_error': 'Mô tả phải từ 10 đến 1000 ký tự nếu có',
      'info_section_name_hint': 'Nhập tiêu đề mô tả rõ ràng...',
      'info_section_name_length_error': 'Tên phải từ 10 đến 200 ký tự',
      'create_btn': 'Tạo mới',
      'update_btn': 'Cập nhật',
      // Location Work Management
      'location_management_title': 'Quản lý địa điểm làm việc',
      'search_location_hint': 'Tìm kiếm theo tên hoặc địa chỉ',
      'add_location_btn': 'Thêm địa điểm làm việc',
      'offline_add_error': 'Không thể thêm khi đang offline',
      'update_status_success': 'Cập nhật trạng thái thành công!',
      'update_status_failed': 'Cập nhật trạng thái thất bại.',
      'add_first_location_hint':
          'Bắt đầu bằng cách thêm địa điểm làm việc đầu tiên',
      'add_first_location_btn': 'Thêm địa điểm đầu tiên',
      'loading_data': 'Đang tải dữ liệu...',
      'create_location_title': 'Tạo địa điểm làm việc',
      'update_location_title': 'Chỉnh sửa địa điểm làm việc',
      'location_name_label': 'Tên địa điểm',
      'location_name_required': 'Vui lòng nhập tên địa điểm',
      'location_name_length_error': 'Tên phải từ 10 đến 200 ký tự',
      'address_label': 'Địa chỉ',
      'address_required': 'Vui lòng nhập địa chỉ',
      'phone_required': 'Vui lòng nhập số điện thoại',
      'phone_invalid': 'Số điện thoại không hợp lệ',
      'timezone_label': 'Múi giờ',
      'timezone_required': 'Vui lòng chọn múi giờ',
      'updating': 'Đang cập nhật...',
      'creating': 'Đang tạo...',
      'update_location_btn': 'Cập nhật địa điểm',
      'create_location_btn': 'Tạo địa điểm',
      'save_location_failed': 'Lưu địa điểm thất bại. Vui lòng thử lại.',
      'confirm_delete_location_message': 'Bạn có chắc chắn muốn xóa địa điểm',
      'delete_location_success': 'Xóa địa điểm thành công!',
      'delete_location_failed': 'Xóa địa điểm thất bại.',

      // Question Management
      'question_management_title': 'Quản lý câu hỏi',
      'search_question_hint': 'Tìm theo tiêu đề, nội dung...',
      'filter_sort_title': 'Bộ lọc & Sắp xếp',
      'all_statuses': 'Tất cả trạng thái',
      'status_pending': 'Đang chờ',
      'status_answered': 'Đã trả lời',
      'status_closed': 'Đã đóng',
      'sort_title': 'Tiêu đề',
      'sort_asc': 'Tăng dần',
      'sort_desc': 'Giảm dần',
      'no_questions_found': 'Không tìm thấy câu hỏi',
      'no_questions_yet': 'Chưa có câu hỏi nào',
      'no_questions_hint': 'Hãy thử tìm kiếm với từ khóa khác hoặc xóa bộ lọc.',
      'no_questions_system_hint':
          'Hiện tại không có câu hỏi nào trong hệ thống.',
      'reload_list': 'Tải lại danh sách',
      'confirm_delete_answer_message':
          'Bạn có chắc chắn muốn xóa câu trả lời này không?',
      'delete_answer_success': 'Đã xóa câu trả lời',
      'delete_answer_failed': 'Xóa câu trả lời thất bại',
      'answer_approved_success': 'Đã duyệt câu trả lời',
      'answer_approved_failed': 'Duyệt câu trả lời thất bại',
      'submit_answer_title': 'Gửi câu trả lời',
      'enter_answer_hint': 'Nhập câu trả lời của bạn...',
      'submit': 'Gửi',
      'answer_submitted_success': 'Đã gửi câu trả lời',
      'answer_submitted_failed': 'Gửi câu trả lời thất bại',
      'edit_answer_title': 'Chỉnh sửa câu trả lời',
      'answer_updated_success': 'Đã cập nhật câu trả lời',
      'answer_updated_failed': 'Cập nhật thất bại',
      'edit_question_title': 'Chỉnh sửa câu hỏi',
      'select_specialty_hint': 'Chọn chuyên khoa',
      'select_status_hint': 'Chọn trạng thái',
      'question_updated_success': 'Đã cập nhật câu hỏi',
      'question_detail_title': 'Chi tiết câu hỏi',
      'status_prefix': 'Trạng thái: ',
      'answers_section_title': 'Câu trả lời',
      'no_answers_yet': 'Chưa có câu trả lời nào',
      'approved_label': 'ĐÃ DUYỆT',
      'doctor_id_prefix': 'Bác sĩ ID: ',
      'approve': 'Duyệt',
      'confirm_delete_question_message': 'Bạn có chắc chắn muốn xóa câu hỏi',
      'action_irreversible': 'Hành động này không thể hoàn tác.',
      'password_min_length_1': 'Mật khẩu phải có ít nhất 1 ký tự',
      'delete_question_success': 'Xóa câu hỏi thành công!',
      // Change Password
      'change_password_success': 'Đổi mật khẩu thành công!',
      'change_password_failed':
          'Đổi mật khẩu thất bại. Vui lòng kiểm tra lại mật khẩu hiện tại.',
      'change_password_instruction':
          'Vui lòng nhập mật khẩu hiện tại và mật khẩu mới của bạn.',
      'current_password': 'Mật khẩu hiện tại',
      'current_password_required': 'Vui lòng nhập mật khẩu hiện tại',
      'new_password': 'Mật khẩu mới',
      'confirm_new_password': 'Xác nhận mật khẩu mới',
      'confirm_new_password_required': 'Vui lòng xác nhận mật khẩu mới',
      'password_mismatch': 'Mật khẩu xác nhận không khớp',
      // Profile
      'role': 'Vai trò',
      'offline_load_error': 'Lỗi kết nối. Đang thử tải dữ liệu cache...',
      'load_profile_error': 'Lỗi khi tải hồ sơ: ',
      'offline_no_cache': 'Bạn đang offline và không có dữ liệu cache.',
      'cannot_load_profile': 'Không thể tải hồ sơ cá nhân.',
      'no_profile_data': 'Không có dữ liệu hồ sơ.',
      // Office Hours
      'office_hours_title': 'Quản lý giờ làm việc',
      'add_office_hour': 'Thêm giờ làm việc',
      'create_office_hour_success': 'Tạo giờ làm việc thành công',
      'delete_office_hour_confirm_title': 'Xác nhận xóa',
      'delete_office_hour_confirm_message':
          'Bạn có chắc chắn muốn xóa giờ làm việc này không?',
      'delete_office_hour_success': 'Đã xóa thành công',
      'global_hours_label': 'Giờ làm việc chung',
      'global_hours_subtitle':
          'Áp dụng cho tất cả địa điểm (không chọn bác sĩ)',
      'doctor_optional': 'Bác sĩ (Tùy chọn)',
      'no_doctor_selected': 'Không chọn bác sĩ',
      'location_optional': 'Địa điểm (Tùy chọn)',
      'day_of_week': 'Ngày trong tuần',
      'start_time': 'Giờ bắt đầu',
      'end_time': 'Giờ kết thúc',
      'create_office_hour_btn': 'Tạo giờ làm việc',
      'no_office_hours_found': 'Không tìm thấy giờ làm việc nào',
      'loading_data_error': 'Lỗi tải dữ liệu: ',
      'monday': 'Thứ Hai',
      'tuesday': 'Thứ Ba',
      'wednesday': 'Thứ Tư',
      'thursday': 'Thứ Năm',
      'friday': 'Thứ Sáu',
      'saturday': 'Thứ Bảy',
      'sunday': 'Chủ Nhật',
      'doctor_at_loc_tab': 'Bác sĩ @ ĐĐ',
      'doctor_only_tab': 'Chỉ Bác sĩ',
      'location_only_tab': 'Chỉ Địa điểm',
      'global_tab': 'Chung',
      'doctor_loc_badge': 'BS & ĐĐ',
      'doctor_badge': 'Bác sĩ',
      'location_badge': 'Địa điểm',
      'am': 'SA',
      'pm': 'CH',
      'global_badge': 'Chung',
      'rule_type_label': 'Loại quy tắc',
      'rule_type_specific': 'Cụ thể (BS @ Địa điểm)',
      'rule_type_doctor_default': 'Mặc định cho Bác sĩ',
      'rule_type_location_default': 'Mặc định cho Địa điểm',
      'rule_type_global_default': 'Mặc định Hệ thống (Chung)',
      'priority_highest': 'Cao nhất',
      'priority_medium': 'Trung bình',
      'priority_low': 'Thấp',
      'priority_lowest': 'Thấp nhất',
      'prev_page': 'Trước',
      'next_page': 'Sau',
      'page_info': 'Trang',
      'google_map_url_label': 'URL Google Map',
      'generate_map_url_tooltip': 'Tạo từ địa chỉ',
      'open_map_tooltip': 'Mở trong Google Maps',
      'invalid_url_error': 'URL không hợp lệ',
      'address_required_for_map_error': 'Cần nhập địa chỉ để tạo URL bản đồ',
      'offline_error': 'Bạn đang offline. Dữ liệu có thể đã cũ.',
      'fetch_users_error': 'Lỗi tải danh sách người dùng.',
      'fetch_groups_error': 'Lỗi tải danh sách nhóm quyền.',
      'create_group_error': 'Không thể tạo nhóm quyền.',
      'update_group_error': 'Không thể cập nhật nhóm quyền.',
      'delete_group_error': 'Không thể xóa nhóm quyền.',
      'fetch_permissions_error': 'Lỗi tải danh sách quyền.',
      'update_permissions_error': 'Lỗi cập nhật quyền.',
      'fetch_stats_error': 'Lỗi tải thống kê.',
      'assign_permission_success': 'Gán quyền thành công',
      'assign_permission_failed': 'Gán quyền thất bại',
      'revoke_permission_success': 'Thu hồi quyền thành công',
      'revoke_permission_failed': 'Không thể thu hồi quyền',
      'search_users_hint': 'Tìm kiếm người dùng...',
      'error_default_group_update': 'Không thể sửa đổi nhóm hệ thống mặc định.',

      'search_groups_hint': 'Tìm kiếm nhóm...',

      'no_offline_data': 'Không có dữ liệu offline',
      'fetch_failed': 'Tải dữ liệu thất bại',
      'fetch_office_hours_failed': 'Không thể tải dữ liệu giờ làm việc',
      'create_office_hour_failed': 'Không thể tạo giờ làm việc',
      'delete_office_hour_failed': 'Không thể xóa giờ làm việc',
      'add_new_office_hour_hint':
          'Nhấn nút "+" ở trên để thêm lịch làm việc mới.',
      'uploading_icon_wait': 'Đang tải biểu tượng, vui lòng đợi...',
      'no_page_route': 'Không có đường dẫn trang được cung cấp',
      'add_item_hint': 'Thêm {item}...',

      'edit_info_title': 'Chỉnh sửa thông tin',
      'confirm_delete_role_message': 'Bạn có chắc chắn muốn xóa ',

      'delete_role_success': 'Xóa {role} thành công!',
      'delete_failed_retry': 'Xóa thất bại. Kiểm tra mật khẩu hoặc thử lại.',
      'enter_pass_prompt': 'Vui lòng nhập mật khẩu',
      'password_min_len': 'Mật khẩu phải có ít nhất 6 ký tự',
      'password_max_len': 'Mật khẩu không được vượt quá 50 ký tự',
      'error_occurred_retry_msg': 'Có lỗi xảy ra. Vui lòng thử lại.',
      'update_profile_succ': 'Cập nhật thông tin thành công!',
      'enter_super_admin_pass': 'Nhập mật khẩu Super Admin',
      'password_hint_range': 'Mật khẩu từ 6-50 ký tự',
    },
  };
}
