// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzdI4bnVn-Fc_ZHUVawiwhuVR3bnM00hI',
    appId: '1:1091939675124:web:0063386eeb56fb8dc327a1',
    messagingSenderId: '1091939675124',
    projectId: 'medicalink-app',
    authDomain: 'medicalink-app.firebaseapp.com',
    storageBucket: 'medicalink-app.firebasestorage.app',
    measurementId: 'G-K710VEG92D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_WxQuQCFPWQW14ddQdF_L5s94epTBffM',
    appId: '1:1091939675124:android:92f3a85ef8e9f60ec327a1',
    messagingSenderId: '1091939675124',
    projectId: 'medicalink-app',
    storageBucket: 'medicalink-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTO4U__ZSYwOXzH_NTbOj6OpT_bkm0iZ0',
    appId: '1:1091939675124:ios:b2832c588cdc30cac327a1',
    messagingSenderId: '1091939675124',
    projectId: 'medicalink-app',
    storageBucket: 'medicalink-app.firebasestorage.app',
    iosBundleId: 'com.example.pbl6mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTO4U__ZSYwOXzH_NTbOj6OpT_bkm0iZ0',
    appId: '1:1091939675124:ios:b2832c588cdc30cac327a1',
    messagingSenderId: '1091939675124',
    projectId: 'medicalink-app',
    storageBucket: 'medicalink-app.firebasestorage.app',
    iosBundleId: 'com.example.pbl6mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzdI4bnVn-Fc_ZHUVawiwhuVR3bnM00hI',
    appId: '1:1091939675124:web:c776cf3ce25b6b85c327a1',
    messagingSenderId: '1091939675124',
    projectId: 'medicalink-app',
    authDomain: 'medicalink-app.firebaseapp.com',
    storageBucket: 'medicalink-app.firebasestorage.app',
    measurementId: 'G-KB8C84D3QP',
  );
}
