/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedAppointmentsRouteRouteImport } from './routes/_authenticated/appointments/route'
import { Route as AuthenticatedWorkLocationsIndexRouteImport } from './routes/_authenticated/work-locations/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedUserPermissionIndexRouteImport } from './routes/_authenticated/user-permission/index'
import { Route as AuthenticatedUserGroupIndexRouteImport } from './routes/_authenticated/user-group/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedStaffsIndexRouteImport } from './routes/_authenticated/staffs/index'
import { Route as AuthenticatedSpecialtiesIndexRouteImport } from './routes/_authenticated/specialties/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReviewsIndexRouteImport } from './routes/_authenticated/reviews/index'
import { Route as AuthenticatedQuestionsIndexRouteImport } from './routes/_authenticated/questions/index'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients.index'
import { Route as AuthenticatedOfficeHoursIndexRouteImport } from './routes/_authenticated/office-hours/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedGroupManagerIndexRouteImport } from './routes/_authenticated/group-manager/index'
import { Route as AuthenticatedDoctorsIndexRouteImport } from './routes/_authenticated/doctors.index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAppointmentsIndexRouteImport } from './routes/_authenticated/appointments/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAppointmentsYearViewRouteImport } from './routes/_authenticated/appointments/year-view'
import { Route as AuthenticatedAppointmentsWeekViewRouteImport } from './routes/_authenticated/appointments/week-view'
import { Route as AuthenticatedAppointmentsMonthViewRouteImport } from './routes/_authenticated/appointments/month-view'
import { Route as AuthenticatedAppointmentsDayViewRouteImport } from './routes/_authenticated/appointments/day-view'
import { Route as AuthenticatedAppointmentsAgendaViewRouteImport } from './routes/_authenticated/appointments/agenda-view'
import { Route as AuthenticatedDoctorsDoctorIdProfileRouteImport } from './routes/_authenticated/doctors/$doctorId.profile'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppointmentsRouteRoute =
  AuthenticatedAppointmentsRouteRouteImport.update({
    id: '/appointments',
    path: '/appointments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkLocationsIndexRoute =
  AuthenticatedWorkLocationsIndexRouteImport.update({
    id: '/work-locations/',
    path: '/work-locations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUserPermissionIndexRoute =
  AuthenticatedUserPermissionIndexRouteImport.update({
    id: '/user-permission/',
    path: '/user-permission/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUserGroupIndexRoute =
  AuthenticatedUserGroupIndexRouteImport.update({
    id: '/user-group/',
    path: '/user-group/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffsIndexRoute =
  AuthenticatedStaffsIndexRouteImport.update({
    id: '/staffs/',
    path: '/staffs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSpecialtiesIndexRoute =
  AuthenticatedSpecialtiesIndexRouteImport.update({
    id: '/specialties/',
    path: '/specialties/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedReviewsIndexRoute =
  AuthenticatedReviewsIndexRouteImport.update({
    id: '/reviews/',
    path: '/reviews/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuestionsIndexRoute =
  AuthenticatedQuestionsIndexRouteImport.update({
    id: '/questions/',
    path: '/questions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOfficeHoursIndexRoute =
  AuthenticatedOfficeHoursIndexRouteImport.update({
    id: '/office-hours/',
    path: '/office-hours/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGroupManagerIndexRoute =
  AuthenticatedGroupManagerIndexRouteImport.update({
    id: '/group-manager/',
    path: '/group-manager/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDoctorsIndexRoute =
  AuthenticatedDoctorsIndexRouteImport.update({
    id: '/doctors/',
    path: '/doctors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppointmentsIndexRoute =
  AuthenticatedAppointmentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppointmentsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppointmentsYearViewRoute =
  AuthenticatedAppointmentsYearViewRouteImport.update({
    id: '/year-view',
    path: '/year-view',
    getParentRoute: () => AuthenticatedAppointmentsRouteRoute,
  } as any)
const AuthenticatedAppointmentsWeekViewRoute =
  AuthenticatedAppointmentsWeekViewRouteImport.update({
    id: '/week-view',
    path: '/week-view',
    getParentRoute: () => AuthenticatedAppointmentsRouteRoute,
  } as any)
const AuthenticatedAppointmentsMonthViewRoute =
  AuthenticatedAppointmentsMonthViewRouteImport.update({
    id: '/month-view',
    path: '/month-view',
    getParentRoute: () => AuthenticatedAppointmentsRouteRoute,
  } as any)
const AuthenticatedAppointmentsDayViewRoute =
  AuthenticatedAppointmentsDayViewRouteImport.update({
    id: '/day-view',
    path: '/day-view',
    getParentRoute: () => AuthenticatedAppointmentsRouteRoute,
  } as any)
const AuthenticatedAppointmentsAgendaViewRoute =
  AuthenticatedAppointmentsAgendaViewRouteImport.update({
    id: '/agenda-view',
    path: '/agenda-view',
    getParentRoute: () => AuthenticatedAppointmentsRouteRoute,
  } as any)
const AuthenticatedDoctorsDoctorIdProfileRoute =
  AuthenticatedDoctorsDoctorIdProfileRouteImport.update({
    id: '/doctors/$doctorId/profile',
    path: '/doctors/$doctorId/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/appointments': typeof AuthenticatedAppointmentsRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/appointments/agenda-view': typeof AuthenticatedAppointmentsAgendaViewRoute
  '/appointments/day-view': typeof AuthenticatedAppointmentsDayViewRoute
  '/appointments/month-view': typeof AuthenticatedAppointmentsMonthViewRoute
  '/appointments/week-view': typeof AuthenticatedAppointmentsWeekViewRoute
  '/appointments/year-view': typeof AuthenticatedAppointmentsYearViewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/appointments/': typeof AuthenticatedAppointmentsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/doctors': typeof AuthenticatedDoctorsIndexRoute
  '/group-manager': typeof AuthenticatedGroupManagerIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/office-hours': typeof AuthenticatedOfficeHoursIndexRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/questions': typeof AuthenticatedQuestionsIndexRoute
  '/reviews': typeof AuthenticatedReviewsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/specialties': typeof AuthenticatedSpecialtiesIndexRoute
  '/staffs': typeof AuthenticatedStaffsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/user-group': typeof AuthenticatedUserGroupIndexRoute
  '/user-permission': typeof AuthenticatedUserPermissionIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/work-locations': typeof AuthenticatedWorkLocationsIndexRoute
  '/doctors/$doctorId/profile': typeof AuthenticatedDoctorsDoctorIdProfileRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/appointments/agenda-view': typeof AuthenticatedAppointmentsAgendaViewRoute
  '/appointments/day-view': typeof AuthenticatedAppointmentsDayViewRoute
  '/appointments/month-view': typeof AuthenticatedAppointmentsMonthViewRoute
  '/appointments/week-view': typeof AuthenticatedAppointmentsWeekViewRoute
  '/appointments/year-view': typeof AuthenticatedAppointmentsYearViewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/appointments': typeof AuthenticatedAppointmentsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/doctors': typeof AuthenticatedDoctorsIndexRoute
  '/group-manager': typeof AuthenticatedGroupManagerIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/office-hours': typeof AuthenticatedOfficeHoursIndexRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/questions': typeof AuthenticatedQuestionsIndexRoute
  '/reviews': typeof AuthenticatedReviewsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/specialties': typeof AuthenticatedSpecialtiesIndexRoute
  '/staffs': typeof AuthenticatedStaffsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/user-group': typeof AuthenticatedUserGroupIndexRoute
  '/user-permission': typeof AuthenticatedUserPermissionIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/work-locations': typeof AuthenticatedWorkLocationsIndexRoute
  '/doctors/$doctorId/profile': typeof AuthenticatedDoctorsDoctorIdProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/appointments': typeof AuthenticatedAppointmentsRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/appointments/agenda-view': typeof AuthenticatedAppointmentsAgendaViewRoute
  '/_authenticated/appointments/day-view': typeof AuthenticatedAppointmentsDayViewRoute
  '/_authenticated/appointments/month-view': typeof AuthenticatedAppointmentsMonthViewRoute
  '/_authenticated/appointments/week-view': typeof AuthenticatedAppointmentsWeekViewRoute
  '/_authenticated/appointments/year-view': typeof AuthenticatedAppointmentsYearViewRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/appointments/': typeof AuthenticatedAppointmentsIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/doctors/': typeof AuthenticatedDoctorsIndexRoute
  '/_authenticated/group-manager/': typeof AuthenticatedGroupManagerIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/office-hours/': typeof AuthenticatedOfficeHoursIndexRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/_authenticated/questions/': typeof AuthenticatedQuestionsIndexRoute
  '/_authenticated/reviews/': typeof AuthenticatedReviewsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/specialties/': typeof AuthenticatedSpecialtiesIndexRoute
  '/_authenticated/staffs/': typeof AuthenticatedStaffsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/user-group/': typeof AuthenticatedUserGroupIndexRoute
  '/_authenticated/user-permission/': typeof AuthenticatedUserPermissionIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/work-locations/': typeof AuthenticatedWorkLocationsIndexRoute
  '/_authenticated/doctors/$doctorId/profile': typeof AuthenticatedDoctorsDoctorIdProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/appointments'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/appointments/agenda-view'
    | '/appointments/day-view'
    | '/appointments/month-view'
    | '/appointments/week-view'
    | '/appointments/year-view'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/appointments/'
    | '/apps'
    | '/chats'
    | '/doctors'
    | '/group-manager'
    | '/help-center'
    | '/office-hours'
    | '/patients'
    | '/questions'
    | '/reviews'
    | '/settings/'
    | '/specialties'
    | '/staffs'
    | '/tasks'
    | '/user-group'
    | '/user-permission'
    | '/users'
    | '/work-locations'
    | '/doctors/$doctorId/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/appointments/agenda-view'
    | '/appointments/day-view'
    | '/appointments/month-view'
    | '/appointments/week-view'
    | '/appointments/year-view'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/appointments'
    | '/apps'
    | '/chats'
    | '/doctors'
    | '/group-manager'
    | '/help-center'
    | '/office-hours'
    | '/patients'
    | '/questions'
    | '/reviews'
    | '/settings'
    | '/specialties'
    | '/staffs'
    | '/tasks'
    | '/user-group'
    | '/user-permission'
    | '/users'
    | '/work-locations'
    | '/doctors/$doctorId/profile'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/appointments'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/appointments/agenda-view'
    | '/_authenticated/appointments/day-view'
    | '/_authenticated/appointments/month-view'
    | '/_authenticated/appointments/week-view'
    | '/_authenticated/appointments/year-view'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/appointments/'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/doctors/'
    | '/_authenticated/group-manager/'
    | '/_authenticated/help-center/'
    | '/_authenticated/office-hours/'
    | '/_authenticated/patients/'
    | '/_authenticated/questions/'
    | '/_authenticated/reviews/'
    | '/_authenticated/settings/'
    | '/_authenticated/specialties/'
    | '/_authenticated/staffs/'
    | '/_authenticated/tasks/'
    | '/_authenticated/user-group/'
    | '/_authenticated/user-permission/'
    | '/_authenticated/users/'
    | '/_authenticated/work-locations/'
    | '/_authenticated/doctors/$doctorId/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments': {
      id: '/_authenticated/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AuthenticatedAppointmentsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work-locations/': {
      id: '/_authenticated/work-locations/'
      path: '/work-locations'
      fullPath: '/work-locations'
      preLoaderRoute: typeof AuthenticatedWorkLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user-permission/': {
      id: '/_authenticated/user-permission/'
      path: '/user-permission'
      fullPath: '/user-permission'
      preLoaderRoute: typeof AuthenticatedUserPermissionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/user-group/': {
      id: '/_authenticated/user-group/'
      path: '/user-group'
      fullPath: '/user-group'
      preLoaderRoute: typeof AuthenticatedUserGroupIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staffs/': {
      id: '/_authenticated/staffs/'
      path: '/staffs'
      fullPath: '/staffs'
      preLoaderRoute: typeof AuthenticatedStaffsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/specialties/': {
      id: '/_authenticated/specialties/'
      path: '/specialties'
      fullPath: '/specialties'
      preLoaderRoute: typeof AuthenticatedSpecialtiesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/reviews/': {
      id: '/_authenticated/reviews/'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthenticatedReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/questions/': {
      id: '/_authenticated/questions/'
      path: '/questions'
      fullPath: '/questions'
      preLoaderRoute: typeof AuthenticatedQuestionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/office-hours/': {
      id: '/_authenticated/office-hours/'
      path: '/office-hours'
      fullPath: '/office-hours'
      preLoaderRoute: typeof AuthenticatedOfficeHoursIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/group-manager/': {
      id: '/_authenticated/group-manager/'
      path: '/group-manager'
      fullPath: '/group-manager'
      preLoaderRoute: typeof AuthenticatedGroupManagerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/doctors/': {
      id: '/_authenticated/doctors/'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof AuthenticatedDoctorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments/': {
      id: '/_authenticated/appointments/'
      path: '/'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AuthenticatedAppointmentsIndexRouteImport
      parentRoute: typeof AuthenticatedAppointmentsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/appointments/year-view': {
      id: '/_authenticated/appointments/year-view'
      path: '/year-view'
      fullPath: '/appointments/year-view'
      preLoaderRoute: typeof AuthenticatedAppointmentsYearViewRouteImport
      parentRoute: typeof AuthenticatedAppointmentsRouteRoute
    }
    '/_authenticated/appointments/week-view': {
      id: '/_authenticated/appointments/week-view'
      path: '/week-view'
      fullPath: '/appointments/week-view'
      preLoaderRoute: typeof AuthenticatedAppointmentsWeekViewRouteImport
      parentRoute: typeof AuthenticatedAppointmentsRouteRoute
    }
    '/_authenticated/appointments/month-view': {
      id: '/_authenticated/appointments/month-view'
      path: '/month-view'
      fullPath: '/appointments/month-view'
      preLoaderRoute: typeof AuthenticatedAppointmentsMonthViewRouteImport
      parentRoute: typeof AuthenticatedAppointmentsRouteRoute
    }
    '/_authenticated/appointments/day-view': {
      id: '/_authenticated/appointments/day-view'
      path: '/day-view'
      fullPath: '/appointments/day-view'
      preLoaderRoute: typeof AuthenticatedAppointmentsDayViewRouteImport
      parentRoute: typeof AuthenticatedAppointmentsRouteRoute
    }
    '/_authenticated/appointments/agenda-view': {
      id: '/_authenticated/appointments/agenda-view'
      path: '/agenda-view'
      fullPath: '/appointments/agenda-view'
      preLoaderRoute: typeof AuthenticatedAppointmentsAgendaViewRouteImport
      parentRoute: typeof AuthenticatedAppointmentsRouteRoute
    }
    '/_authenticated/doctors/$doctorId/profile': {
      id: '/_authenticated/doctors/$doctorId/profile'
      path: '/doctors/$doctorId/profile'
      fullPath: '/doctors/$doctorId/profile'
      preLoaderRoute: typeof AuthenticatedDoctorsDoctorIdProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAppointmentsRouteRouteChildren {
  AuthenticatedAppointmentsAgendaViewRoute: typeof AuthenticatedAppointmentsAgendaViewRoute
  AuthenticatedAppointmentsDayViewRoute: typeof AuthenticatedAppointmentsDayViewRoute
  AuthenticatedAppointmentsMonthViewRoute: typeof AuthenticatedAppointmentsMonthViewRoute
  AuthenticatedAppointmentsWeekViewRoute: typeof AuthenticatedAppointmentsWeekViewRoute
  AuthenticatedAppointmentsYearViewRoute: typeof AuthenticatedAppointmentsYearViewRoute
  AuthenticatedAppointmentsIndexRoute: typeof AuthenticatedAppointmentsIndexRoute
}

const AuthenticatedAppointmentsRouteRouteChildren: AuthenticatedAppointmentsRouteRouteChildren =
  {
    AuthenticatedAppointmentsAgendaViewRoute:
      AuthenticatedAppointmentsAgendaViewRoute,
    AuthenticatedAppointmentsDayViewRoute:
      AuthenticatedAppointmentsDayViewRoute,
    AuthenticatedAppointmentsMonthViewRoute:
      AuthenticatedAppointmentsMonthViewRoute,
    AuthenticatedAppointmentsWeekViewRoute:
      AuthenticatedAppointmentsWeekViewRoute,
    AuthenticatedAppointmentsYearViewRoute:
      AuthenticatedAppointmentsYearViewRoute,
    AuthenticatedAppointmentsIndexRoute: AuthenticatedAppointmentsIndexRoute,
  }

const AuthenticatedAppointmentsRouteRouteWithChildren =
  AuthenticatedAppointmentsRouteRoute._addFileChildren(
    AuthenticatedAppointmentsRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppointmentsRouteRoute: typeof AuthenticatedAppointmentsRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedDoctorsIndexRoute: typeof AuthenticatedDoctorsIndexRoute
  AuthenticatedGroupManagerIndexRoute: typeof AuthenticatedGroupManagerIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedOfficeHoursIndexRoute: typeof AuthenticatedOfficeHoursIndexRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
  AuthenticatedQuestionsIndexRoute: typeof AuthenticatedQuestionsIndexRoute
  AuthenticatedReviewsIndexRoute: typeof AuthenticatedReviewsIndexRoute
  AuthenticatedSpecialtiesIndexRoute: typeof AuthenticatedSpecialtiesIndexRoute
  AuthenticatedStaffsIndexRoute: typeof AuthenticatedStaffsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUserGroupIndexRoute: typeof AuthenticatedUserGroupIndexRoute
  AuthenticatedUserPermissionIndexRoute: typeof AuthenticatedUserPermissionIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWorkLocationsIndexRoute: typeof AuthenticatedWorkLocationsIndexRoute
  AuthenticatedDoctorsDoctorIdProfileRoute: typeof AuthenticatedDoctorsDoctorIdProfileRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppointmentsRouteRoute:
    AuthenticatedAppointmentsRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedDoctorsIndexRoute: AuthenticatedDoctorsIndexRoute,
  AuthenticatedGroupManagerIndexRoute: AuthenticatedGroupManagerIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedOfficeHoursIndexRoute: AuthenticatedOfficeHoursIndexRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
  AuthenticatedQuestionsIndexRoute: AuthenticatedQuestionsIndexRoute,
  AuthenticatedReviewsIndexRoute: AuthenticatedReviewsIndexRoute,
  AuthenticatedSpecialtiesIndexRoute: AuthenticatedSpecialtiesIndexRoute,
  AuthenticatedStaffsIndexRoute: AuthenticatedStaffsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUserGroupIndexRoute: AuthenticatedUserGroupIndexRoute,
  AuthenticatedUserPermissionIndexRoute: AuthenticatedUserPermissionIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWorkLocationsIndexRoute: AuthenticatedWorkLocationsIndexRoute,
  AuthenticatedDoctorsDoctorIdProfileRoute:
    AuthenticatedDoctorsDoctorIdProfileRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
